// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package types

import "github.com/wjojf/go-uber-fx/internal/domain/users/models"

type Mutation struct {
}

type Query struct {
}

type User struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

func NewUser(u models.User) *User {
	return &User{
		ID:    u.ID(),
		Name:  u.Username(),
		Email: "",
	}
}

type UserCreateInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type UserUpdateInput struct {
	ID         string  `json:"id"`
	Name       *string `json:"name,omitempty"`
	Email      *string `json:"email,omitempty"`
	Password   *string `json:"password,omitempty"`
	IsVerified *bool   `json:"isVerified,omitempty"`
}
