// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package types

import "github.com/wjojf/go-uber-fx/internal/domain/users/models"

type Mutation struct {
}

type Query struct {
}

type User struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

func NewUser(user models.User) *User {
	return &User{
		ID:    user.ID(),
		Name:  user.Username(),
		Email: "todo",
	}
}


type UserCreateInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

func (cu UserCreateInput) ToDomain() (models.UserValueObject, error) {
	return models.NewUserValueObject(
		cu.Name, cu.Email, cu.Password, false,
	)
}


type UserUpdateInput struct {
	ID         string  `json:"id"`
	Name       *string `json:"name,omitempty"`
	Email      *string `json:"email,omitempty"`
	Password   *string `json:"password,omitempty"`
	IsVerified *bool   `json:"isVerified,omitempty"`
}
