package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"github.com/pkg/errors"

	"github.com/wjojf/go-uber-fx/internal/api/graphql/types"
	"github.com/wjojf/go-uber-fx/internal/domain/users/models"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input types.UserCreateInput) (*types.User, error) {

	// Convert input to value object
	vo, err := input.ToVO(false)
	if err != nil {
		return nil, err
	}

	// Create user
	user, err := r.r.SaveUser(ctx, vo)
	if err != nil {
		return nil, err
	}

	return types.NewUser(user), nil

}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, input types.UserUpdateInput) (*types.User, error) {

	vo, err := input.ToVO()
	if err != nil {
		return nil, err
	}

	user, err := r.r.UpdateUserByID(ctx, input.ID, vo)
	if err != nil {
		return nil, err
	}

	return types.NewUser(user), nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (*types.User, error) {
	return nil, errors.Wrap(errors.New("not implemented"), "DeleteUser")
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*types.User, error) {

	var usersResponse []*types.User
	var users []models.User

	// Get users from the repository
	users, err := r.r.GetAllUsers(ctx)
	if err != nil {
		return nil, err
	}

	// Convert users to response
	for _, user := range users {
		usersResponse = append(usersResponse, types.NewUser(user))
	}

	return usersResponse, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*types.User, error) {

	var user models.User
	var err error

	if user, err = r.r.GetUserByID(ctx, id); err != nil {
		return nil, err
	}

	return types.NewUser(user), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
